[project]
name = "scientist-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.3.4",
    "jupyterlab-quarto>=0.3.5",
    "nbdev>=2.3.34",
    "ruff>=0.9.3",
]
