# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/scientist-notebook',
                'doc_host': 'https://duoan.github.io',
                'git_url': 'https://github.com/duoan/scientist-notebook',
                'lib_path': 'scientist_notebook'},
  'syms': {'scientist_notebook.core': {'scientist_notebook.core.foo': ('core.html#foo', 'scientist_notebook/core.py')}}}
